name: Protected Zone
main: me.ryall.ProtectedZone.ProtectedZone
version: 1
description: Flexible and Powerful Zone Protection
commands:
  PZ:
    description: Controls the Protection Zone plugin
    usage: /pz (info|claim|release|add <user>|remove <user>|owner <user>)